#+Title: open issues
* bugs
1. start date isn't doing anything here.
2. [X] we should be able to choose up to 3 leaders.
3. [X] when exporting, it is not using the rounded numbers. 
* features
1. [X] as a user, i should be able to input either a 1rm or a training max for a lift.
   1. [X] currently, the aplication assumes that we're always inputting a 1rm
   2. [X] this choice should be a radio button and should be properly reflect by the ui
   3. [X] why does this matter? this may make more sense once we're in the midst of a long running program once we're working largely based off of our TM instead of a 1rm.
   4. the name input type isn't that satisfying here, but it works for now.
2. [X] users should be able to configure their TM % as a relationship to their 1 rep max.
   1. Currently, the underlying type allows for an input, but the program itself just defaults to 85%.
   2. [X] Users should be able to input a value in the range of 80-90%.
3. [X] As a user, I want to export my table to google sheets.
   1. [X] I should be able to choose if I want to export to a new sheet or append to an existing one.
   2. [X] in the case of a new spreadsheet, i should be able to designate a name
   3. [X] users should be able to view all available spreadsheets
      1. [X] can we scope this further such that we only look at spreadsheets associated to this application?
	 1. since we have to first query google drive then filter down on the spreadsheet api, this gets expensive. Using some normalized name of files would solve this but it is a little clunkier. I think this is an OK approach for our purposes.
   4. [X] if choosing an existing spreadsheet, we should auto-populate the training maxes from the last 7th week protocol
4. [X] there should be multiple sheets.
   1. [X] one that represents a complete history
   2. [X] one that represents the current training block
5. [-] The identity should be persisted across sessions.
   1. [X] ultimately this means we'll need a database. sqlite or some inmemory provider should be fine
   2. [X] we should be caching the token data retrieved by google
   3. [X] in the case of an expired user token, we should use the refresh token to get accesso
      1. [X] this should be done when the user is opening the website
      2. [X] it should be a non-blocking operation
      3. [X] it should be apparent to the user that the backend is performing some auth related action
   4. [ ] is this done securely?
	 
6. [X] when the application has the user credential, it should be reflected on the website itself. The login button shouldn't really appear.
   1. this has  been done to an extent, but the website now requires google based auth.
   2. Ideally, there should just be a header with a login button at the top of the page. Which would then reflect the users identity in the case that they're logged in.
