#+Title: open issues
* bugs
1. start date isn't doing anything here.
2. [X] we should be able to choose up to 3 leaders.
3. [X] when exporting, it is not using the rounded numbers. 
* features
1. [X] as a user, i should be able to input either a 1rm or a training max for a lift.
   1. [X] currently, the application assumes that we're always inputting a 1rm
   2. [X] this choice should be a radio button and should be properly reflect by the ui
   3. [X] why does this matter? this may make more sense once we're in the midst of a long running program once we're working largely based off of our TM instead of a 1rm.
   4. the name input type isn't that satisfying here, but it works for now.
2. [X] users should be able to configure their TM % as a relationship to their 1 rep max.
   1. Currently, the underlying type allows for an input, but the program itself just defaults to 85%.
   2. Users should be able to input a value in the range of 80-90%.
3. [ ] given an external data store, users should be able to append cycles to that store. 
   1. for the first iteration of this feature, let's use google sheets as as the target SDK.
   2. if a user provides a google sheet, we should be able to dump the program into it
